seth_abi = [
    {
        "constant": False,
        "inputs": [],
        "name": "resume",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "name",
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "stop",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "hasInitialized",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_spender", "type": "address"}, {"name": "_amount", "type": "uint256"}],
        "name": "approve",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "STAKING_CONTROL_ROLE",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "totalSupply",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_ethAmount", "type": "uint256"}],
        "name": "getSharesByPooledEth",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "isStakingPaused",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_sender", "type": "address"},
            {"name": "_recipient", "type": "address"},
            {"name": "_amount", "type": "uint256"},
        ],
        "name": "transferFrom",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_script", "type": "bytes"}],
        "name": "getEVMScriptExecutor",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_maxStakeLimit", "type": "uint256"},
            {"name": "_stakeLimitIncreasePerBlock", "type": "uint256"},
        ],
        "name": "setStakingLimit",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "RESUME_ROLE",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_lidoLocator", "type": "address"}, {"name": "_eip712StETH", "type": "address"}],
        "name": "finalizeUpgrade_v2",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "decimals",
        "outputs": [{"name": "", "type": "uint8"}],
        "payable": False,
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getRecoveryVault",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "DOMAIN_SEPARATOR",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getTotalPooledEther",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_newDepositedValidators", "type": "uint256"}],
        "name": "unsafeChangeDepositedValidators",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "PAUSE_ROLE",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_spender", "type": "address"}, {"name": "_addedValue", "type": "uint256"}],
        "name": "increaseAllowance",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getTreasury",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "isStopped",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getBufferedEther",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_lidoLocator", "type": "address"}, {"name": "_eip712StETH", "type": "address"}],
        "name": "initialize",
        "outputs": [],
        "payable": True,
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "receiveELRewards",
        "outputs": [],
        "payable": True,
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getWithdrawalCredentials",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getCurrentStakeLimit",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getStakeLimitFullInfo",
        "outputs": [
            {"name": "isStakingPaused", "type": "bool"},
            {"name": "isStakingLimitSet", "type": "bool"},
            {"name": "currentStakeLimit", "type": "uint256"},
            {"name": "maxStakeLimit", "type": "uint256"},
            {"name": "maxStakeLimitGrowthBlocks", "type": "uint256"},
            {"name": "prevStakeLimit", "type": "uint256"},
            {"name": "prevStakeBlockNumber", "type": "uint256"},
        ],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_sender", "type": "address"},
            {"name": "_recipient", "type": "address"},
            {"name": "_sharesAmount", "type": "uint256"},
        ],
        "name": "transferSharesFrom",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_account", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "resumeStaking",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getFeeDistribution",
        "outputs": [
            {"name": "treasuryFeeBasisPoints", "type": "uint16"},
            {"name": "insuranceFeeBasisPoints", "type": "uint16"},
            {"name": "operatorsFeeBasisPoints", "type": "uint16"},
        ],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "receiveWithdrawals",
        "outputs": [],
        "payable": True,
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_sharesAmount", "type": "uint256"}],
        "name": "getPooledEthByShares",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "token", "type": "address"}],
        "name": "allowRecoverability",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "owner", "type": "address"}],
        "name": "nonces",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "appId",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getOracle",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "eip712Domain",
        "outputs": [
            {"name": "name", "type": "string"},
            {"name": "version", "type": "string"},
            {"name": "chainId", "type": "uint256"},
            {"name": "verifyingContract", "type": "address"},
        ],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getContractVersion",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getInitializationBlock",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_recipient", "type": "address"}, {"name": "_sharesAmount", "type": "uint256"}],
        "name": "transferShares",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "symbol",
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getEIP712StETH",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "", "type": "address"}],
        "name": "transferToVault",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [
            {"name": "_sender", "type": "address"},
            {"name": "_role", "type": "bytes32"},
            {"name": "_params", "type": "uint256[]"},
        ],
        "name": "canPerform",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_referral", "type": "address"}],
        "name": "submit",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": True,
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_spender", "type": "address"}, {"name": "_subtractedValue", "type": "uint256"}],
        "name": "decreaseAllowance",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getEVMScriptRegistry",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"name": "_recipient", "type": "address"}, {"name": "_amount", "type": "uint256"}],
        "name": "transfer",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_maxDepositsCount", "type": "uint256"},
            {"name": "_stakingModuleId", "type": "uint256"},
            {"name": "_depositCalldata", "type": "bytes"},
        ],
        "name": "deposit",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "UNSAFE_CHANGE_DEPOSITED_VALIDATORS_ROLE",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getBeaconStat",
        "outputs": [
            {"name": "depositedValidators", "type": "uint256"},
            {"name": "beaconValidators", "type": "uint256"},
            {"name": "beaconBalance", "type": "uint256"},
        ],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "removeStakingLimit",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_reportTimestamp", "type": "uint256"},
            {"name": "_timeElapsed", "type": "uint256"},
            {"name": "_clValidators", "type": "uint256"},
            {"name": "_clBalance", "type": "uint256"},
            {"name": "_withdrawalVaultBalance", "type": "uint256"},
            {"name": "_elRewardsVaultBalance", "type": "uint256"},
            {"name": "_sharesRequestedToBurn", "type": "uint256"},
            {"name": "_withdrawalFinalizationBatches", "type": "uint256[]"},
            {"name": "_simulatedShareRate", "type": "uint256"},
        ],
        "name": "handleOracleReport",
        "outputs": [{"name": "postRebaseAmounts", "type": "uint256[4]"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getFee",
        "outputs": [{"name": "totalFee", "type": "uint16"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "kernel",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getTotalShares",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"name": "_owner", "type": "address"},
            {"name": "_spender", "type": "address"},
            {"name": "_value", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_v", "type": "uint8"},
            {"name": "_r", "type": "bytes32"},
            {"name": "_s", "type": "bytes32"},
        ],
        "name": "permit",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_owner", "type": "address"}, {"name": "_spender", "type": "address"}],
        "name": "allowance",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "isPetrified",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getLidoLocator",
        "outputs": [{"name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "canDeposit",
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "STAKING_PAUSE_ROLE",
        "outputs": [{"name": "", "type": "bytes32"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getDepositableEther",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [{"name": "_account", "type": "address"}],
        "name": "sharesOf",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "pauseStaking",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "getTotalELRewardsCollected",
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {"payable": True, "stateMutability": "payable", "type": "fallback"},
    {"anonymous": False, "inputs": [], "name": "StakingPaused", "type": "event"},
    {"anonymous": False, "inputs": [], "name": "StakingResumed", "type": "event"},
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "name": "maxStakeLimit", "type": "uint256"},
            {"indexed": False, "name": "stakeLimitIncreasePerBlock", "type": "uint256"},
        ],
        "name": "StakingLimitSet",
        "type": "event",
    },
    {"anonymous": False, "inputs": [], "name": "StakingLimitRemoved", "type": "event"},
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "reportTimestamp", "type": "uint256"},
            {"indexed": False, "name": "preCLValidators", "type": "uint256"},
            {"indexed": False, "name": "postCLValidators", "type": "uint256"},
        ],
        "name": "CLValidatorsUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "depositedValidators", "type": "uint256"}],
        "name": "DepositedValidatorsChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "reportTimestamp", "type": "uint256"},
            {"indexed": False, "name": "preCLBalance", "type": "uint256"},
            {"indexed": False, "name": "postCLBalance", "type": "uint256"},
            {"indexed": False, "name": "withdrawalsWithdrawn", "type": "uint256"},
            {"indexed": False, "name": "executionLayerRewardsWithdrawn", "type": "uint256"},
            {"indexed": False, "name": "postBufferedEther", "type": "uint256"},
        ],
        "name": "ETHDistributed",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "reportTimestamp", "type": "uint256"},
            {"indexed": False, "name": "timeElapsed", "type": "uint256"},
            {"indexed": False, "name": "preTotalShares", "type": "uint256"},
            {"indexed": False, "name": "preTotalEther", "type": "uint256"},
            {"indexed": False, "name": "postTotalShares", "type": "uint256"},
            {"indexed": False, "name": "postTotalEther", "type": "uint256"},
            {"indexed": False, "name": "sharesMintedAsFees", "type": "uint256"},
        ],
        "name": "TokenRebased",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "lidoLocator", "type": "address"}],
        "name": "LidoLocatorSet",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "amount", "type": "uint256"}],
        "name": "ELRewardsReceived",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "amount", "type": "uint256"}],
        "name": "WithdrawalsReceived",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "sender", "type": "address"},
            {"indexed": False, "name": "amount", "type": "uint256"},
            {"indexed": False, "name": "referral", "type": "address"},
        ],
        "name": "Submitted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "amount", "type": "uint256"}],
        "name": "Unbuffered",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "executor", "type": "address"},
            {"indexed": False, "name": "script", "type": "bytes"},
            {"indexed": False, "name": "input", "type": "bytes"},
            {"indexed": False, "name": "returnData", "type": "bytes"},
        ],
        "name": "ScriptResult",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "vault", "type": "address"},
            {"indexed": True, "name": "token", "type": "address"},
            {"indexed": False, "name": "amount", "type": "uint256"},
        ],
        "name": "RecoverToVault",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "eip712StETH", "type": "address"}],
        "name": "EIP712StETHInitialized",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "from", "type": "address"},
            {"indexed": True, "name": "to", "type": "address"},
            {"indexed": False, "name": "sharesValue", "type": "uint256"},
        ],
        "name": "TransferShares",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "account", "type": "address"},
            {"indexed": False, "name": "preRebaseTokenAmount", "type": "uint256"},
            {"indexed": False, "name": "postRebaseTokenAmount", "type": "uint256"},
            {"indexed": False, "name": "sharesAmount", "type": "uint256"},
        ],
        "name": "SharesBurnt",
        "type": "event",
    },
    {"anonymous": False, "inputs": [], "name": "Stopped", "type": "event"},
    {"anonymous": False, "inputs": [], "name": "Resumed", "type": "event"},
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "from", "type": "address"},
            {"indexed": True, "name": "to", "type": "address"},
            {"indexed": False, "name": "value", "type": "uint256"},
        ],
        "name": "Transfer",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "owner", "type": "address"},
            {"indexed": True, "name": "spender", "type": "address"},
            {"indexed": False, "name": "value", "type": "uint256"},
        ],
        "name": "Approval",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "name": "version", "type": "uint256"}],
        "name": "ContractVersionSet",
        "type": "event",
    },
]
