jobs:
  FBTC:
    initialization_tasks:
    - init_token_price
    - init_period_address_token_balance

    regular_tasks:
      - daily_feature_holding_balance_staked_fbtc_detail.sql
      - daily_feature_holding_balance_uniswap_v3.sql
      - daily_address_token_balances.sql
      - daily_feature_erc20_token_supply_records.sql

    ordered_tasks:
      - period_address_token_balances.sql
      - period_feature_holding_balance_uniswap_v3.sql:
          - agin_position_token_address: 0x218bf598d1453383e2f4aa7b14ffb9bfb102d637
          - cleoexchange_position_token_address: 0xaaa78e8c4241990b4ce159e105da08129345946a
      - period_feature_staked_fbtc_detail_records.sql
      - period_feature_holding_balance_staked_fbtc_detail.sql
      - period_feature_erc1155_token_supply_records.sql
      - period_feature_holding_balance_merchantmoe.sql
      - period_feature_erc20_token_supply_records.sql
      - period_feature_holding_balance_dodo.sql:
          - token_address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
      - period_feature_holding_balance_lendle.sql
      - period_feature_defi_wallet_fbtc_aggregates.py
  EXPLORE:
    regular_tasks:
      - daily_explore_aggregates.sql


schedule:
  common_config:
    schedule_time: 0 1 * * *

  schedule1:
    jobs:
      FBTC

  schedule2:
    config:
      schedule_time: 0 2 * * * # default 0 1 * * *
    jobs:
      EXPLORE