chain_name: mantle

FBTC:
  period_sqls:
    address_token_balance:
      - period_address_token_balances

  py_jobs:
    - address_token_balance
    - uniswapv3
    - merchantmoe
    - init_capital
    - lendle
    - staked
    - dodo

cmETH:
  period_sqls:
    address_token_balance:
      - period_address_token_balances

  py_jobs:
    - address_token_balance
    - uniswapv3
    - merchantmoe
    - init_capital
    - lendle
    - staked