"""add user ops table

Revision ID: 9a1e927f02bb
Revises: 3d5ce8939570
Create Date: 2024-07-31 13:11:10.244802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a1e927f02bb'
down_revision: Union[str, None] = '3d5ce8939570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_operations_results',
    sa.Column('user_op_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=42), nullable=True),
    sa.Column('paymaster', sa.VARCHAR(length=42), nullable=True),
    sa.Column('nonce', sa.NUMERIC(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('actual_gas_cost', sa.NUMERIC(), nullable=True),
    sa.Column('actual_gas_used', sa.INTEGER(), nullable=True),
    sa.Column('init_code', postgresql.BYTEA(), nullable=True),
    sa.Column('call_data', postgresql.BYTEA(), nullable=True),
    sa.Column('call_gas_limit', sa.INTEGER(), nullable=True),
    sa.Column('verification_gas_limit', sa.INTEGER(), nullable=True),
    sa.Column('pre_verification_gas', sa.INTEGER(), nullable=True),
    sa.Column('max_fee_per_gas', sa.INTEGER(), nullable=True),
    sa.Column('max_priority_fee_per_gas', sa.INTEGER(), nullable=True),
    sa.Column('paymaster_and_data', postgresql.BYTEA(), nullable=True),
    sa.Column('signature', postgresql.BYTEA(), nullable=True),
    sa.Column('transactions_hash', postgresql.BYTEA(), nullable=True),
    sa.Column('transactions_index', sa.INTEGER(), nullable=True),
    sa.Column('block_number', sa.INTEGER(), nullable=True),
    sa.Column('block_timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('bundler', sa.VARCHAR(length=42), nullable=True),
    sa.Column('start_log_index', sa.INTEGER(), nullable=True),
    sa.Column('end_log_index', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('user_op_hash')
    )
    op.create_index('transactions_hash_index', 'user_operations_results', ['transactions_hash'], unique=False)
    op.drop_index('feature_uniswap_v3_tokens_nft_index', table_name='feature_uniswap_v3_tokens')
    op.drop_table('feature_uniswap_v3_tokens')
    op.drop_table('feature_uniswap_v3_pools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_uniswap_v3_pools',
    sa.Column('nft_address', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('token0_address', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('token1_address', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=True),
    sa.Column('tick_spacing', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=True),
    sa.Column('mint_block_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nft_address', 'pool_address', name='feature_uniswap_v3_pools_pkey')
    )
    op.create_table('feature_uniswap_v3_tokens',
    sa.Column('nft_address', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('tick_lower', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=True),
    sa.Column('tick_upper', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(precision=100, scale=0), autoincrement=False, nullable=True),
    sa.Column('mint_block_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nft_address', 'token_id', name='feature_uniswap_v3_tokens_pkey')
    )
    op.create_index('feature_uniswap_v3_tokens_nft_index', 'feature_uniswap_v3_tokens', ['nft_address'], unique=False)
    op.drop_index('transactions_hash_index', table_name='user_operations_results')
    op.drop_table('user_operations_results')
    # ### end Alembic commands ###
