"""add_token_balances_table

Revision ID: 0cbfd0a6b259
Revises: 3171c9a82b2a
Create Date: 2024-05-23 17:15:11.047444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cbfd0a6b259'
down_revision: Union[str, None] = '3171c9a82b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_token_balances',
    sa.Column('address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=78), nullable=True),
    sa.Column('token_type', sa.VARCHAR(), nullable=True),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'token_address', 'block_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_token_balances')
    # ### end Alembic commands ###
