"""add contracts table

Revision ID: 96bccfafdb77
Revises: 0cbfd0a6b259
Create Date: 2024-05-28 20:30:39.940618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96bccfafdb77'
down_revision: Union[str, None] = '0cbfd0a6b259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('address', postgresql.BYTEA(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('contract_creator', postgresql.BYTEA(), nullable=True),
    sa.Column('creation_code', postgresql.BYTEA(), nullable=True),
    sa.Column('deployed_code', postgresql.BYTEA(), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_hash', postgresql.BYTEA(), nullable=True),
    sa.Column('block_timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('transaction_index', sa.INTEGER(), nullable=True),
    sa.Column('transaction_hash', postgresql.BYTEA(), nullable=True),
    sa.Column('official_website', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('social_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_proxy', sa.BOOLEAN(), nullable=True),
    sa.Column('implementation_contract', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_implementation_contract', sa.BOOLEAN(), nullable=True),
    sa.Column('proxy_standard', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
