"""ens

Revision ID: 9542dc714cfe
Revises: bf51d23c852f
Create Date: 2024-08-28 17:53:52.897188

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9542dc714cfe"
down_revision: Union[str, None] = "bf51d23c852f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ens_middle",
        sa.Column("transaction_hash", sa.String(), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("block_hash", sa.String(), nullable=True),
        sa.Column("block_timestamp", sa.TIMESTAMP(), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("event_name", sa.String(), nullable=True),
        sa.Column("from_address", sa.String(), nullable=True),
        sa.Column("to_address", sa.String(), nullable=True),
        sa.Column("base_node", sa.String(), nullable=True),
        sa.Column("node", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("expires", sa.TIMESTAMP(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("resolver", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("reverse_base_node", sa.String(), nullable=True),
        sa.Column("reverse_node", sa.String(), nullable=True),
        sa.Column("reverse_label", sa.String(), nullable=True),
        sa.Column("reverse_name", sa.String(), nullable=True),
        sa.Column("create_time", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("update_time", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("reorg", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("transaction_hash", "log_index", name="ens_tnx_log_index"),
    )
    op.create_index(
        "ens_idx_block_number_log_index", "ens_middle", ["block_number", sa.text("log_index DESC")], unique=False
    )
    op.create_table(
        "ens_rel",
        sa.Column("node", sa.String(), nullable=False),
        sa.Column("token_id", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("expires", sa.TIMESTAMP(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("reverse_name", sa.String(), nullable=True),
        sa.Column("inserted_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("node"),
        sa.UniqueConstraint("node"),
    )
    op.create_index("ens_idx_address", "ens_rel", ["address"], unique=False)
    op.create_index("ens_idx_name", "ens_rel", ["name"], unique=False)
    op.create_index("ens_idx_reverse_name", "ens_rel", ["reverse_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ens_idx_reverse_name", table_name="ens_rel")
    op.drop_index("ens_idx_name", table_name="ens_rel")
    op.drop_index("ens_idx_address", table_name="ens_rel")
    op.drop_table("ens_rel")
    op.drop_index("ens_idx_block_number_log_index", table_name="ens_middle")
    op.drop_table("ens_middle")
    # ### end Alembic commands ###
