"""add period_feature_holding_balance_satlayer_fbtc

Revision ID: 04262e1a7f87
Revises: e1c68e3705e2
Create Date: 2024-09-20 14:23:19.146897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04262e1a7f87'
down_revision: Union[str, None] = 'e1c68e3705e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_feature_holding_balance_satlayer_fbtc',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'wallet_address', 'protocol_id', 'contract_address')
    )

    op.add_column('period_feature_holding_balance_uniswap_v3', sa.Column('token0_balance_upper', sa.NUMERIC(precision=100, scale=18), nullable=True))
    op.add_column('period_feature_holding_balance_uniswap_v3', sa.Column('token0_balance_lower', sa.NUMERIC(precision=100, scale=18), nullable=True))
    op.add_column('period_feature_holding_balance_uniswap_v3', sa.Column('token1_balance_upper', sa.NUMERIC(precision=100, scale=18), nullable=True))
    op.add_column('period_feature_holding_balance_uniswap_v3', sa.Column('token1_balance_lower', sa.NUMERIC(precision=100, scale=18), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_feature_holding_balance_uniswap_v3', 'token1_balance_lower')
    op.drop_column('period_feature_holding_balance_uniswap_v3', 'token1_balance_upper')
    op.drop_column('period_feature_holding_balance_uniswap_v3', 'token0_balance_lower')
    op.drop_column('period_feature_holding_balance_uniswap_v3', 'token0_balance_upper')

    op.drop_table('period_feature_holding_balance_satlayer_fbtc')
    # ### end Alembic commands ###
