"""add uniswap v3 pool factory_address

Revision ID: 0043891d8824
Revises: c7e9d498f0d9
Create Date: 2024-08-30 12:01:43.330767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0043891d8824"
down_revision: Union[str, None] = "c7e9d498f0d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_uniswap_v3_pool_current_prices", sa.Column("factory_address", postgresql.BYTEA(), nullable=True)
    )
    op.add_column("feature_uniswap_v3_pool_prices", sa.Column("factory_address", postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature_uniswap_v3_pool_prices", "factory_address")
    op.drop_column("feature_uniswap_v3_pool_current_prices", "factory_address")
    # ### end Alembic commands ###
