"""add_failure_records_table

Revision ID: f846e3abeb18
Revises: 3bd2e3099bae
Create Date: 2024-11-21 21:37:25.662986

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f846e3abeb18"
down_revision: Union[str, None] = "3bd2e3099bae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failure_records",
        sa.Column("record_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("mission_sign", sa.VARCHAR(), nullable=True),
        sa.Column("output_types", sa.VARCHAR(), nullable=True),
        sa.Column("start_block_number", sa.BIGINT(), nullable=True),
        sa.Column("end_block_number", sa.BIGINT(), nullable=True),
        sa.Column("exception_stage", sa.VARCHAR(), nullable=True),
        sa.Column("exception", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("crash_time", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("record_id"),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failure_records", if_exists=True)
    # ### end Alembic commands ###
