"""add current_traits_activeness

Revision ID: b86e241b5e18
Revises: 832fa52da346
Create Date: 2024-08-06 14:03:13.234591

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b86e241b5e18"
down_revision: Union[str, None] = "832fa52da346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_traits_activeness",
        sa.Column("block_number", sa.BIGINT(), nullable=False),
        sa.Column("address", postgresql.BYTEA(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("create_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("update_time", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("current_traits_activeness")
    # ### end Alembic commands ###
