"""add fbtc table

Revision ID: 01dbb9035d35
Revises: 2359a28d63cb
Create Date: 2024-09-03 13:16:06.557026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01dbb9035d35'
down_revision: Union[str, None] = '2359a28d63cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_address_token_balances',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=78), nullable=False),
    sa.Column('token_type', sa.VARCHAR(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'address', 'token_address', 'token_id')
    )
    op.create_table('daily_feature_erc1155_token_holdings',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'token_address', 'wallet_address', 'token_id')
    )
    op.create_table('daily_feature_erc1155_token_supply_records',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'token_address', 'token_id')
    )
    op.create_table('daily_feature_erc20_token_supply_records',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'token_address')
    )
    op.create_table('daily_feature_holding_balance_dodo',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance_of', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('total_supply', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token0_address', sa.String(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', sa.String(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'protocol_id', 'contract_address', 'wallet_address')
    )
    op.create_table('daily_feature_holding_balance_lendle',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('token_symbol', sa.String(), nullable=False),
    sa.Column('token_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'wallet_address', 'protocol_id', 'contract_address')
    )
    op.create_table('daily_feature_holding_balance_merchantmoe',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_address', sa.String(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', sa.String(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'protocol_id', 'contract_address', 'token_id', 'wallet_address')
    )
    op.create_table('daily_feature_holding_balance_staked_fbtc_detail',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'wallet_address', 'protocol_id', 'contract_address')
    )
    op.create_table('daily_feature_holding_balance_uniswap_v3',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_address', sa.String(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', sa.String(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'protocol_id', 'contract_address', 'token_id')
    )
    op.create_table('daily_feature_merchant_moe_token_bin_records',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('reserve0_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'token_address', 'token_id')
    )
    op.create_table('daily_feature_uniswap_v3_pool_prices',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('sqrt_price_x96', sa.NUMERIC(precision=78), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'pool_address')
    )
    op.create_index('daily_feature_uniswap_v3_pool_prices_block_date_index', 'daily_feature_uniswap_v3_pool_prices', ['block_date'], unique=False)
    op.create_table('daily_feature_uniswap_v3_token_details',
    sa.Column('block_date', sa.DATE(), nullable=False),
    sa.Column('nft_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('liquidity', sa.NUMERIC(precision=78), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('block_date', 'nft_address', 'token_id')
    )
    op.create_index('daily_feature_uniswap_v3_token_details_block_date_index', 'daily_feature_uniswap_v3_token_details', ['block_date'], unique=False)
    op.create_table('feature_erc1155_token_current_holdings',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'wallet_address')
    )
    op.create_index('feature_erc1155_token_current_holdings_token_block_desc_index', 'feature_erc1155_token_current_holdings', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_index('feature_erc1155_token_current_holdings_wallet_block_desc_index', 'feature_erc1155_token_current_holdings', [sa.text('wallet_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_table('feature_erc1155_token_current_supply_status',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id')
    )
    op.create_table('feature_erc1155_token_holdings',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'wallet_address', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_erc1155_token_holding_token_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_index('feature_erc1155_token_holding_token_wallet_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.create_table('feature_erc1155_token_supply_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_erc1155_token_supply_token_block_desc_index', 'feature_erc1155_token_supply_records', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_table('feature_erc20_current_token_holdings',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('wallet_address', 'token_address')
    )
    op.create_index('feature_erc20_current_token_holdings_token_balance_index', 'feature_erc20_current_token_holdings', ['token_address', sa.text('balance DESC')], unique=False)
    op.create_table('feature_erc20_current_total_supply_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token_address')
    )
    op.create_table('feature_erc20_token_holdings',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'wallet_address', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_erc20_token_holdings_token_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_index('feature_erc20_token_holdings_token_wallet_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.create_table('feature_erc20_total_supply_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'block_timestamp', 'block_number')
    )
    op.create_table('feature_merchant_moe_pools',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('token0_address', postgresql.BYTEA(), nullable=True),
    sa.Column('token1_address', postgresql.BYTEA(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address')
    )
    op.create_table('feature_merchant_moe_token_bin_current_status',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('reserve0_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id')
    )
    op.create_index('feature_merchant_moe_token_bin_current_status_token_id_index', 'feature_merchant_moe_token_bin_current_status', [sa.text('token_address DESC'), sa.text('token_id ASC')], unique=False)
    op.create_table('feature_merchant_moe_token_bin_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('reserve0_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_merchant_moe_token_bin_records_token_block_desc_index', 'feature_merchant_moe_token_bin_records', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_table('feature_staked_fbtc_detail_records',
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('contract_address', 'wallet_address', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_staked_fbtc_detail_records_protocol_block_desc_index', 'feature_staked_fbtc_detail_records', [sa.text('protocol_id DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_index('feature_staked_fbtc_detail_records_wallet_block_desc_index', 'feature_staked_fbtc_detail_records', [sa.text('wallet_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_table('feature_staked_fbtc_status',
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('contract_address', 'wallet_address')
    )
    op.create_index('feature_staked_fbtc_status_protocol_block_desc_index', 'feature_staked_fbtc_status', [sa.text('protocol_id DESC')], unique=False)
    op.create_index('feature_staked_fbtc_status_wallet_block_desc_index', 'feature_staked_fbtc_status', [sa.text('wallet_address DESC')], unique=False)
    op.create_table('feature_uniswap_v2_liquidity_current_holdings',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('wallet_address', 'pool_address')
    )
    op.create_index('feature_uniswap_v2_liquidity_current_holdings_balance_index', 'feature_uniswap_v2_liquidity_current_holdings', ['pool_address', sa.text('balance DESC')], unique=False)
    op.create_table('feature_uniswap_v2_liquidity_holding_records',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('pool_address', 'wallet_address', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('block_number DESC')], unique=False)
    op.create_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.create_table('feature_uniswap_v2_pool_current_reserves',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('reserve0', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('block_timestamp_last', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pool_address')
    )
    op.create_table('feature_uniswap_v2_pool_reserves_records',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('reserve0', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('block_timestamp_last', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('pool_address', 'block_timestamp', 'block_number')
    )
    op.create_table('feature_uniswap_v2_pool_total_supply_records',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('pool_address', 'block_timestamp', 'block_number')
    )
    op.create_table('feature_uniswap_v2_pools_current_total_supply',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pool_address')
    )
    op.create_table('feature_uniswap_v3_pool_current_prices',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('factory_address', postgresql.BYTEA(), nullable=True),
    sa.Column('sqrt_price_x96', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('tick', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pool_address')
    )
    op.create_table('feature_uniswap_v3_pool_prices',
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('sqrt_price_x96', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('tick', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('factory_address', postgresql.BYTEA(), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('pool_address', 'block_timestamp', 'block_number')
    )
    op.create_table('feature_uniswap_v3_token_current_status',
    sa.Column('nft_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=True),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=True),
    sa.Column('liquidity', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('nft_address', 'token_id')
    )
    op.create_index('feature_uniswap_v3_token_current_status_wallet_desc_index', 'feature_uniswap_v3_token_current_status', [sa.text('wallet_address DESC')], unique=False)
    op.create_table('feature_uniswap_v3_token_details',
    sa.Column('nft_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=True),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=True),
    sa.Column('liquidity', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('nft_address', 'token_id', 'block_timestamp', 'block_number')
    )
    op.create_index('feature_uniswap_v3_token_details_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('nft_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('wallet_address DESC'), sa.text('nft_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.create_table('period_address_token_balances',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=78), nullable=False),
    sa.Column('token_type', sa.VARCHAR(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'address', 'token_address', 'token_id')
    )
    op.create_table('period_feature_defi_fbtc_aggregates',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('chain_name', sa.String(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('total_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('total_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('day_user_count', sa.INTEGER(), nullable=True),
    sa.Column('total_user_count', sa.INTEGER(), nullable=True),
    sa.Column('updated_version', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'chain_name', 'protocol_id')
    )
    op.create_index('period_feature_defi_fbtc_aggregates_period_date', 'period_feature_defi_fbtc_aggregates', ['period_date'], unique=False)
    op.create_table('period_feature_defi_wallet_fbtc_detail',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('chain_name', sa.String(), nullable=False),
    sa.Column('contracts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('total_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('wallet_holding_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('wallet_holding_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('updated_version', sa.INTEGER(), nullable=True),
    sa.Column('total_protocol_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('total_protocol_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'wallet_address', 'chain_name')
    )
    op.create_index('period_feature_uniswap_v3_wallet_fbtc_detail_period_date', 'period_feature_defi_wallet_fbtc_detail', ['period_date'], unique=False)
    op.create_table('period_feature_erc1155_token_holdings',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'token_address', 'wallet_address', 'token_id')
    )
    op.create_table('period_feature_erc1155_token_supply_records',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'token_address', 'token_id')
    )
    op.create_table('period_feature_erc20_token_supply_records',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'token_address')
    )
    op.create_table('period_feature_holding_balance_dodo',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance_of', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('total_supply', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token0_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'protocol_id', 'contract_address', 'wallet_address')
    )
    op.create_table('period_feature_holding_balance_lendle',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_symbol', sa.VARCHAR(), nullable=True),
    sa.Column('token_address', postgresql.BYTEA(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'wallet_address', 'protocol_id', 'contract_address')
    )
    op.create_table('period_feature_holding_balance_merchantmoe',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'protocol_id', 'contract_address', 'token_id', 'wallet_address')
    )
    op.create_table('period_feature_holding_balance_staked_fbtc_detail',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'wallet_address', 'protocol_id', 'contract_address')
    )
    op.create_table('period_feature_holding_balance_uniswap_v3',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_symbol', sa.String(), nullable=False),
    sa.Column('token0_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('token1_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token1_symbol', sa.String(), nullable=False),
    sa.Column('token1_balance', sa.NUMERIC(precision=100, scale=18), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'protocol_id', 'contract_address', 'token_id')
    )
    op.create_index('period_feature_holding_balance_uniswap_v3_period_date', 'period_feature_holding_balance_uniswap_v3', ['period_date'], unique=False)
    op.create_table('period_feature_merchant_moe_token_bin_records',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('reserve0_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'token_address', 'token_id')
    )
    op.create_table('period_feature_staked_fbtc_detail_records',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('protocol_id', sa.VARCHAR(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'contract_address', 'wallet_address')
    )
    op.create_index('period_feature_staked_fbtc_detail_records_wallet_period_date', 'period_feature_staked_fbtc_detail_records', ['period_date'], unique=False)
    op.create_table('period_feature_uniswap_v3_pool_prices',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('sqrt_price_x96', sa.NUMERIC(precision=78), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'pool_address')
    )
    op.create_index('Period_feature_uniswap_v3_pool_prices_period_date_index', 'period_feature_uniswap_v3_pool_prices', ['period_date'], unique=False)
    op.create_table('period_feature_uniswap_v3_token_details',
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('nft_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('pool_address', postgresql.BYTEA(), nullable=False),
    sa.Column('liquidity', sa.NUMERIC(precision=78), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('period_date', 'nft_address', 'token_id')
    )
    op.create_index('daily_feature_uniswap_v3_token_details_period_date_index', 'period_feature_uniswap_v3_token_details', ['period_date'], unique=False)
    op.create_index('daily_wallet_addresses_aggregates_block_date_index', 'daily_wallet_addresses_aggregates', ['block_date'], unique=False)
    op.add_column('feature_blue_chip_holders', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.add_column('feature_blue_chip_holders', sa.Column('block_timestamp', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('feature_blue_chip_holders', 'called_block_number')
    op.drop_column('feature_blue_chip_holders', 'called_block_timestamp')
    op.add_column('feature_uniswap_v2_pools', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v2_pools', 'called_block_number')
    op.add_column('feature_uniswap_v3_pools', sa.Column('factory_address', postgresql.BYTEA(), nullable=True))
    op.add_column('feature_uniswap_v3_pools', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.add_column('feature_uniswap_v3_pools', sa.Column('block_timestamp', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v3_pools', 'called_block_number')
    op.add_column('feature_uniswap_v3_tokens', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.add_column('feature_uniswap_v3_tokens', sa.Column('block_timestamp', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v3_tokens', 'called_block_number')
    op.create_index('period_wallet_addresses_aggregates_period_date_index', 'period_wallet_addresses_aggregates', ['period_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('period_wallet_addresses_aggregates_period_date_index', table_name='period_wallet_addresses_aggregates')
    op.add_column('feature_uniswap_v3_tokens', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v3_tokens', 'block_timestamp')
    op.drop_column('feature_uniswap_v3_tokens', 'block_number')
    op.add_column('feature_uniswap_v3_pools', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v3_pools', 'block_timestamp')
    op.drop_column('feature_uniswap_v3_pools', 'block_number')
    op.drop_column('feature_uniswap_v3_pools', 'factory_address')
    op.add_column('feature_uniswap_v2_pools', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v2_pools', 'block_number')
    op.add_column('feature_blue_chip_holders', sa.Column('called_block_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('feature_blue_chip_holders', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_blue_chip_holders', 'block_timestamp')
    op.drop_column('feature_blue_chip_holders', 'block_number')
    op.drop_index('daily_wallet_addresses_aggregates_block_date_index', table_name='daily_wallet_addresses_aggregates')
    op.drop_index('daily_feature_uniswap_v3_token_details_period_date_index', table_name='period_feature_uniswap_v3_token_details')
    op.drop_table('period_feature_uniswap_v3_token_details')
    op.drop_index('Period_feature_uniswap_v3_pool_prices_period_date_index', table_name='period_feature_uniswap_v3_pool_prices')
    op.drop_table('period_feature_uniswap_v3_pool_prices')
    op.drop_index('period_feature_staked_fbtc_detail_records_wallet_period_date', table_name='period_feature_staked_fbtc_detail_records')
    op.drop_table('period_feature_staked_fbtc_detail_records')
    op.drop_table('period_feature_merchant_moe_token_bin_records')
    op.drop_index('period_feature_holding_balance_uniswap_v3_period_date', table_name='period_feature_holding_balance_uniswap_v3')
    op.drop_table('period_feature_holding_balance_uniswap_v3')
    op.drop_table('period_feature_holding_balance_staked_fbtc_detail')
    op.drop_table('period_feature_holding_balance_merchantmoe')
    op.drop_table('period_feature_holding_balance_lendle')
    op.drop_table('period_feature_holding_balance_dodo')
    op.drop_table('period_feature_erc20_token_supply_records')
    op.drop_table('period_feature_erc1155_token_supply_records')
    op.drop_table('period_feature_erc1155_token_holdings')
    op.drop_index('period_feature_uniswap_v3_wallet_fbtc_detail_period_date', table_name='period_feature_defi_wallet_fbtc_detail')
    op.drop_table('period_feature_defi_wallet_fbtc_detail')
    op.drop_index('period_feature_defi_fbtc_aggregates_period_date', table_name='period_feature_defi_fbtc_aggregates')
    op.drop_table('period_feature_defi_fbtc_aggregates')
    op.drop_table('period_address_token_balances')
    op.drop_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.drop_index('feature_uniswap_v3_token_details_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.drop_table('feature_uniswap_v3_token_details')
    op.drop_index('feature_uniswap_v3_token_current_status_wallet_desc_index', table_name='feature_uniswap_v3_token_current_status')
    op.drop_table('feature_uniswap_v3_token_current_status')
    op.drop_table('feature_uniswap_v3_pool_prices')
    op.drop_table('feature_uniswap_v3_pool_current_prices')
    op.drop_table('feature_uniswap_v2_pools_current_total_supply')
    op.drop_table('feature_uniswap_v2_pool_total_supply_records')
    op.drop_table('feature_uniswap_v2_pool_reserves_records')
    op.drop_table('feature_uniswap_v2_pool_current_reserves')
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.drop_table('feature_uniswap_v2_liquidity_holding_records')
    op.drop_index('feature_uniswap_v2_liquidity_current_holdings_balance_index', table_name='feature_uniswap_v2_liquidity_current_holdings')
    op.drop_table('feature_uniswap_v2_liquidity_current_holdings')
    op.drop_index('feature_staked_fbtc_status_wallet_block_desc_index', table_name='feature_staked_fbtc_status')
    op.drop_index('feature_staked_fbtc_status_protocol_block_desc_index', table_name='feature_staked_fbtc_status')
    op.drop_table('feature_staked_fbtc_status')
    op.drop_index('feature_staked_fbtc_detail_records_wallet_block_desc_index', table_name='feature_staked_fbtc_detail_records')
    op.drop_index('feature_staked_fbtc_detail_records_protocol_block_desc_index', table_name='feature_staked_fbtc_detail_records')
    op.drop_table('feature_staked_fbtc_detail_records')
    op.drop_index('feature_merchant_moe_token_bin_records_token_block_desc_index', table_name='feature_merchant_moe_token_bin_records')
    op.drop_table('feature_merchant_moe_token_bin_records')
    op.drop_index('feature_merchant_moe_token_bin_current_status_token_id_index', table_name='feature_merchant_moe_token_bin_current_status')
    op.drop_table('feature_merchant_moe_token_bin_current_status')
    op.drop_table('feature_merchant_moe_pools')
    op.drop_table('feature_erc20_total_supply_records')
    op.drop_index('feature_erc20_token_holdings_token_wallet_block_desc_index', table_name='feature_erc20_token_holdings')
    op.drop_index('feature_erc20_token_holdings_token_block_desc_index', table_name='feature_erc20_token_holdings')
    op.drop_table('feature_erc20_token_holdings')
    op.drop_table('feature_erc20_current_total_supply_records')
    op.drop_index('feature_erc20_current_token_holdings_token_balance_index', table_name='feature_erc20_current_token_holdings')
    op.drop_table('feature_erc20_current_token_holdings')
    op.drop_index('feature_erc1155_token_supply_token_block_desc_index', table_name='feature_erc1155_token_supply_records')
    op.drop_table('feature_erc1155_token_supply_records')
    op.drop_index('feature_erc1155_token_holding_token_wallet_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.drop_index('feature_erc1155_token_holding_token_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.drop_table('feature_erc1155_token_holdings')
    op.drop_table('feature_erc1155_token_current_supply_status')
    op.drop_index('feature_erc1155_token_current_holdings_wallet_block_desc_index', table_name='feature_erc1155_token_current_holdings')
    op.drop_index('feature_erc1155_token_current_holdings_token_block_desc_index', table_name='feature_erc1155_token_current_holdings')
    op.drop_table('feature_erc1155_token_current_holdings')
    op.drop_index('daily_feature_uniswap_v3_token_details_block_date_index', table_name='daily_feature_uniswap_v3_token_details')
    op.drop_table('daily_feature_uniswap_v3_token_details')
    op.drop_index('daily_feature_uniswap_v3_pool_prices_block_date_index', table_name='daily_feature_uniswap_v3_pool_prices')
    op.drop_table('daily_feature_uniswap_v3_pool_prices')
    op.drop_table('daily_feature_merchant_moe_token_bin_records')
    op.drop_table('daily_feature_holding_balance_uniswap_v3')
    op.drop_table('daily_feature_holding_balance_staked_fbtc_detail')
    op.drop_table('daily_feature_holding_balance_merchantmoe')
    op.drop_table('daily_feature_holding_balance_lendle')
    op.drop_table('daily_feature_holding_balance_dodo')
    op.drop_table('daily_feature_erc20_token_supply_records')
    op.drop_table('daily_feature_erc1155_token_supply_records')
    op.drop_table('daily_feature_erc1155_token_holdings')
    op.drop_table('daily_address_token_balances')
    # ### end Alembic commands ###
