"""add merchant moe detail table

Revision ID: 87ebc3fcd9ca
Revises: 2961c81d0b50
Create Date: 2024-08-16 15:45:45.529350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ebc3fcd9ca'
down_revision: Union[str, None] = '2961c81d0b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_erc1155_token_holdings',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('called_block_number', sa.BIGINT(), nullable=False),
    sa.Column('called_block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'wallet_address', 'called_block_timestamp', 'called_block_number')
    )
    op.create_index('feature_erc1155_token_holding_token_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.create_index('feature_erc1155_token_holding_token_wallet_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('called_block_number DESC')], unique=False)
    op.create_table('feature_erc1155_token_supply_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('called_block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('called_block_number', sa.BIGINT(), nullable=False),
    sa.Column('total_supply', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'called_block_timestamp', 'called_block_number')
    )
    op.create_index('feature_erc1155_token_supply_token_block_desc_index', 'feature_erc1155_token_supply_records', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.create_table('feature_merchant_moe_token_bin_records',
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token_id', sa.NUMERIC(precision=100), nullable=False),
    sa.Column('called_block_timestamp', sa.BIGINT(), nullable=False),
    sa.Column('called_block_number', sa.BIGINT(), nullable=False),
    sa.Column('reserve0_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('reserve1_bin', sa.NUMERIC(precision=100), nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('token_address', 'token_id', 'called_block_timestamp', 'called_block_number')
    )
    op.create_index('feature_merchant_moe_token_bin_records_token_block_desc_index', 'feature_merchant_moe_token_bin_records', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('feature_merchant_moe_token_bin_records_token_block_desc_index', table_name='feature_merchant_moe_token_bin_records')
    op.drop_table('feature_merchant_moe_token_bin_records')
    op.drop_index('feature_erc1155_token_supply_token_block_desc_index', table_name='feature_erc1155_token_supply_records')
    op.drop_table('feature_erc1155_token_supply_records')
    op.drop_index('feature_erc1155_token_holding_token_wallet_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.drop_index('feature_erc1155_token_holding_token_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.drop_table('feature_erc1155_token_holdings')
    # ### end Alembic commands ###
