"""add daily fbtc tables

Revision ID: fed5929f40ed
Revises: 8ed65fe65ee5
Create Date: 2024-08-23 11:31:32.686127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fed5929f40ed'
down_revision: Union[str, None] = '8ed65fe65ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_feature_defi_wallet_fbtc_detail',
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('period_date', sa.DATE(), nullable=False),
    sa.Column('chain_name', sa.String(), nullable=False),
    sa.Column('contracts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('total_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('wallet_holding_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('wallet_holding_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('updated_version', sa.INTEGER(), nullable=True),
    sa.Column('total_protocol_fbtc_balance', sa.NUMERIC(), nullable=True),
    sa.Column('total_protocol_fbtc_usd', sa.NUMERIC(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('protocol_id', 'wallet_address', 'period_date', 'chain_name')
    )
    op.create_index('period_feature_uniswap_v3_wallet_fbtc_detail_period_date', 'period_feature_defi_wallet_fbtc_detail', ['period_date'], unique=False)
    op.create_table('token_price',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=78), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.add_column('daily_wallet_addresses_aggregates', sa.Column('token_balance', sa.NUMERIC(precision=78), nullable=True))
    op.add_column('feature_blue_chip_holders', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.add_column('feature_blue_chip_holders', sa.Column('block_timestamp', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('feature_blue_chip_holders', 'called_block_number')
    op.drop_column('feature_blue_chip_holders', 'called_block_timestamp')
    op.add_column('feature_erc1155_token_holdings', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc1155_token_holdings', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc1155_token_holdings', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_erc1155_token_holding_token_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.create_index('feature_erc1155_token_holding_token_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_index('feature_erc1155_token_holding_token_wallet_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.create_index('feature_erc1155_token_holding_token_wallet_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.drop_column('feature_erc1155_token_holdings', 'called_block_number')
    op.drop_column('feature_erc1155_token_holdings', 'called_block_timestamp')
    op.add_column('feature_erc1155_token_supply_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc1155_token_supply_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc1155_token_supply_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_erc1155_token_supply_token_block_desc_index', table_name='feature_erc1155_token_supply_records')
    op.create_index('feature_erc1155_token_supply_token_block_desc_index', 'feature_erc1155_token_supply_records', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_column('feature_erc1155_token_supply_records', 'called_block_number')
    op.drop_column('feature_erc1155_token_supply_records', 'called_block_timestamp')
    op.add_column('feature_erc20_token_holdings', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc20_token_holdings', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc20_token_holdings', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_erc20_token_holdings_token_block_desc_index', table_name='feature_erc20_token_holdings')
    op.create_index('feature_erc20_token_holdings_token_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_index('feature_erc20_token_holdings_token_wallet_block_desc_index', table_name='feature_erc20_token_holdings')
    op.create_index('feature_erc20_token_holdings_token_wallet_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.drop_column('feature_erc20_token_holdings', 'called_block_number')
    op.drop_column('feature_erc20_token_holdings', 'called_block_timestamp')
    op.add_column('feature_erc20_total_supply_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc20_total_supply_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_erc20_total_supply_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_column('feature_erc20_total_supply_records', 'called_block_number')
    op.drop_column('feature_erc20_total_supply_records', 'called_block_timestamp')
    op.add_column('feature_merchant_moe_token_bin_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_merchant_moe_token_bin_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_merchant_moe_token_bin_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_merchant_moe_token_bin_records_token_block_desc_index', table_name='feature_merchant_moe_token_bin_records')
    op.create_index('feature_merchant_moe_token_bin_records_token_block_desc_index', 'feature_merchant_moe_token_bin_records', [sa.text('token_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_column('feature_merchant_moe_token_bin_records', 'called_block_number')
    op.drop_column('feature_merchant_moe_token_bin_records', 'called_block_timestamp')
    op.add_column('feature_staked_fbtc_detail_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.add_column('feature_uniswap_v2_liquidity_holding_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_liquidity_holding_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_liquidity_holding_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.create_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('block_number DESC')], unique=False)
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.create_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('wallet_address DESC'), sa.text('block_number DESC')], unique=False)
    op.drop_column('feature_uniswap_v2_liquidity_holding_records', 'called_block_number')
    op.drop_column('feature_uniswap_v2_liquidity_holding_records', 'called_block_timestamp')
    op.add_column('feature_uniswap_v2_pool_reserves_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_pool_reserves_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_pool_reserves_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_column('feature_uniswap_v2_pool_reserves_records', 'called_block_number')
    op.drop_column('feature_uniswap_v2_pool_reserves_records', 'called_block_timestamp')
    op.add_column('feature_uniswap_v2_pool_total_supply_records', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_pool_total_supply_records', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v2_pool_total_supply_records', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_column('feature_uniswap_v2_pool_total_supply_records', 'called_block_number')
    op.drop_column('feature_uniswap_v2_pool_total_supply_records', 'called_block_timestamp')
    op.add_column('feature_uniswap_v2_pools', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v2_pools', 'called_block_number')
    op.add_column('feature_uniswap_v3_pool_prices', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v3_pool_prices', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v3_pool_prices', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_column('feature_uniswap_v3_pool_prices', 'called_block_number')
    op.drop_column('feature_uniswap_v3_pool_prices', 'called_block_timestamp')
    op.add_column('feature_uniswap_v3_pools', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v3_pools', 'called_block_number')
    op.add_column('feature_uniswap_v3_token_details', sa.Column('block_number', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v3_token_details', sa.Column('block_timestamp', sa.BIGINT(), nullable=False))
    op.add_column('feature_uniswap_v3_token_details', sa.Column('reorg', sa.BOOLEAN(), nullable=True))
    op.drop_index('feature_uniswap_v3_token_details_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.create_index('feature_uniswap_v3_token_details_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('nft_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.create_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('wallet_address DESC'), sa.text('nft_address DESC'), sa.text('block_timestamp DESC')], unique=False)
    op.drop_column('feature_uniswap_v3_token_details', 'called_block_number')
    op.drop_column('feature_uniswap_v3_token_details', 'called_block_timestamp')
    op.add_column('feature_uniswap_v3_tokens', sa.Column('block_number', sa.BIGINT(), nullable=True))
    op.drop_column('feature_uniswap_v3_tokens', 'called_block_number')
    op.add_column('period_feature_uniswap_v3_wallet_address_amount', sa.Column('protocol_id', sa.String(), nullable=False))
    op.add_column('period_wallet_addresses_aggregates', sa.Column('token_balance', sa.NUMERIC(precision=78), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_wallet_addresses_aggregates', 'token_balance')
    op.drop_column('period_feature_uniswap_v3_wallet_address_amount', 'protocol_id')
    op.add_column('feature_uniswap_v3_tokens', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v3_tokens', 'block_number')
    op.add_column('feature_uniswap_v3_token_details', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_uniswap_v3_token_details', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.create_index('feature_uniswap_v3_token_details_wallet_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('wallet_address DESC'), sa.text('nft_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_index('feature_uniswap_v3_token_details_token_block_desc_index', table_name='feature_uniswap_v3_token_details')
    op.create_index('feature_uniswap_v3_token_details_token_block_desc_index', 'feature_uniswap_v3_token_details', [sa.text('nft_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_column('feature_uniswap_v3_token_details', 'reorg')
    op.drop_column('feature_uniswap_v3_token_details', 'block_timestamp')
    op.drop_column('feature_uniswap_v3_token_details', 'block_number')
    op.add_column('feature_uniswap_v3_pools', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v3_pools', 'block_number')
    op.add_column('feature_uniswap_v3_pool_prices', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_uniswap_v3_pool_prices', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('feature_uniswap_v3_pool_prices', 'reorg')
    op.drop_column('feature_uniswap_v3_pool_prices', 'block_timestamp')
    op.drop_column('feature_uniswap_v3_pool_prices', 'block_number')
    op.add_column('feature_uniswap_v2_pools', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_uniswap_v2_pools', 'block_number')
    op.add_column('feature_uniswap_v2_pool_total_supply_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_uniswap_v2_pool_total_supply_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('feature_uniswap_v2_pool_total_supply_records', 'reorg')
    op.drop_column('feature_uniswap_v2_pool_total_supply_records', 'block_timestamp')
    op.drop_column('feature_uniswap_v2_pool_total_supply_records', 'block_number')
    op.add_column('feature_uniswap_v2_pool_reserves_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_uniswap_v2_pool_reserves_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('feature_uniswap_v2_pool_reserves_records', 'reorg')
    op.drop_column('feature_uniswap_v2_pool_reserves_records', 'block_timestamp')
    op.drop_column('feature_uniswap_v2_pool_reserves_records', 'block_number')
    op.add_column('feature_uniswap_v2_liquidity_holding_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_uniswap_v2_liquidity_holding_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.create_index('feature_uniswap_v2_liquidity_holding_records_wallet_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('wallet_address DESC'), sa.text('called_block_number DESC')], unique=False)
    op.drop_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', table_name='feature_uniswap_v2_liquidity_holding_records')
    op.create_index('feature_uniswap_v2_liquidity_holding_records_pool_b_dindex', 'feature_uniswap_v2_liquidity_holding_records', [sa.text('pool_address DESC'), sa.text('called_block_number DESC')], unique=False)
    op.drop_column('feature_uniswap_v2_liquidity_holding_records', 'reorg')
    op.drop_column('feature_uniswap_v2_liquidity_holding_records', 'block_timestamp')
    op.drop_column('feature_uniswap_v2_liquidity_holding_records', 'block_number')
    op.drop_column('feature_staked_fbtc_detail_records', 'reorg')
    op.add_column('feature_merchant_moe_token_bin_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_merchant_moe_token_bin_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_merchant_moe_token_bin_records_token_block_desc_index', table_name='feature_merchant_moe_token_bin_records')
    op.create_index('feature_merchant_moe_token_bin_records_token_block_desc_index', 'feature_merchant_moe_token_bin_records', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_column('feature_merchant_moe_token_bin_records', 'reorg')
    op.drop_column('feature_merchant_moe_token_bin_records', 'block_number')
    op.drop_column('feature_merchant_moe_token_bin_records', 'block_timestamp')
    op.add_column('feature_erc20_total_supply_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_erc20_total_supply_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('feature_erc20_total_supply_records', 'reorg')
    op.drop_column('feature_erc20_total_supply_records', 'block_timestamp')
    op.drop_column('feature_erc20_total_supply_records', 'block_number')
    op.add_column('feature_erc20_token_holdings', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_erc20_token_holdings', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_erc20_token_holdings_token_wallet_block_desc_index', table_name='feature_erc20_token_holdings')
    op.create_index('feature_erc20_token_holdings_token_wallet_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('called_block_number DESC')], unique=False)
    op.drop_index('feature_erc20_token_holdings_token_block_desc_index', table_name='feature_erc20_token_holdings')
    op.create_index('feature_erc20_token_holdings_token_block_desc_index', 'feature_erc20_token_holdings', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_column('feature_erc20_token_holdings', 'reorg')
    op.drop_column('feature_erc20_token_holdings', 'block_timestamp')
    op.drop_column('feature_erc20_token_holdings', 'block_number')
    op.add_column('feature_erc1155_token_supply_records', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_erc1155_token_supply_records', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_erc1155_token_supply_token_block_desc_index', table_name='feature_erc1155_token_supply_records')
    op.create_index('feature_erc1155_token_supply_token_block_desc_index', 'feature_erc1155_token_supply_records', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_column('feature_erc1155_token_supply_records', 'reorg')
    op.drop_column('feature_erc1155_token_supply_records', 'block_number')
    op.drop_column('feature_erc1155_token_supply_records', 'block_timestamp')
    op.add_column('feature_erc1155_token_holdings', sa.Column('called_block_timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('feature_erc1155_token_holdings', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index('feature_erc1155_token_holding_token_wallet_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.create_index('feature_erc1155_token_holding_token_wallet_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('wallet_address DESC'), sa.text('called_block_number DESC')], unique=False)
    op.drop_index('feature_erc1155_token_holding_token_block_desc_index', table_name='feature_erc1155_token_holdings')
    op.create_index('feature_erc1155_token_holding_token_block_desc_index', 'feature_erc1155_token_holdings', [sa.text('token_address DESC'), sa.text('called_block_timestamp DESC')], unique=False)
    op.drop_column('feature_erc1155_token_holdings', 'reorg')
    op.drop_column('feature_erc1155_token_holdings', 'block_timestamp')
    op.drop_column('feature_erc1155_token_holdings', 'block_number')
    op.add_column('feature_blue_chip_holders', sa.Column('called_block_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('feature_blue_chip_holders', sa.Column('called_block_number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('feature_blue_chip_holders', 'block_timestamp')
    op.drop_column('feature_blue_chip_holders', 'block_number')
    op.drop_column('daily_wallet_addresses_aggregates', 'token_balance')
    op.drop_table('token_price')
    op.drop_index('period_feature_uniswap_v3_wallet_fbtc_detail_period_date', table_name='period_feature_defi_wallet_fbtc_detail')
    op.drop_table('period_feature_defi_wallet_fbtc_detail')
    # ### end Alembic commands ###
