"""ens

Revision ID: 6c07c41aa30d
Revises: bf51d23c852f
Create Date: 2024-08-30 10:43:25.984842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c07c41aa30d'
down_revision: Union[str, None] = 'bf51d23c852f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ens_address',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reverse_node', sa.String(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('ens_middle',
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('block_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('base_node', sa.String(), nullable=True),
    sa.Column('node', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('expires', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('resolver', sa.String(), nullable=True),
    sa.Column('registrant', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('reverse_base_node', sa.String(), nullable=True),
    sa.Column('reverse_node', sa.String(), nullable=True),
    sa.Column('reverse_label', sa.String(), nullable=True),
    sa.Column('reverse_name', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('w_token_id', sa.String(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reorg', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_hash', 'log_index', name='ens_tnx_log_index')
    )
    op.create_index('ens_idx_block_number_log_index', 'ens_middle', ['block_number', sa.text('log_index DESC')], unique=False)
    op.create_table('ens_record',
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('w_token_id', sa.String(), nullable=True),
    sa.Column('first_owned_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('registration', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires', sa.TIMESTAMP(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('node'),
    sa.UniqueConstraint('node')
    )
    op.create_index('ens_idx_address', 'ens_record', ['address'], unique=False)
    op.create_index('ens_idx_name', 'ens_record', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ens_idx_name', table_name='ens_record')
    op.drop_index('ens_idx_address', table_name='ens_record')
    op.drop_table('ens_record')
    op.drop_index('ens_idx_block_number_log_index', table_name='ens_middle')
    op.drop_table('ens_middle')
    op.drop_table('ens_address')
    # ### end Alembic commands ###
