"""add stakedFbtc record table

Revision ID: fd2804696e09
Revises: 7ddc78bd2fe7
Create Date: 2024-08-21 14:15:51.260754

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd2804696e09"
down_revision: Union[str, None] = "7ddc78bd2fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_staked_fbtc_detail_records",
        sa.Column("contract_address", postgresql.BYTEA(), nullable=False),
        sa.Column("wallet_address", postgresql.BYTEA(), nullable=False),
        sa.Column("log_index", sa.BIGINT(), nullable=False),
        sa.Column("block_number", sa.BIGINT(), nullable=False),
        sa.Column("block_timestamp", sa.BIGINT(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=100), nullable=True),
        sa.Column("protocol_id", sa.VARCHAR(), nullable=True),
        sa.Column("create_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("update_time", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("contract_address", "wallet_address", "block_timestamp", "block_number", "log_index"),
    )
    op.create_index(
        "feature_staked_fbtc_detail_records_protocol_block_desc_index",
        "feature_staked_fbtc_detail_records",
        [sa.text("protocol_id DESC"), sa.text("block_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "feature_staked_fbtc_detail_records_wallet_block_desc_index",
        "feature_staked_fbtc_detail_records",
        [sa.text("wallet_address DESC"), sa.text("block_timestamp DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "feature_staked_fbtc_detail_records_wallet_block_desc_index", table_name="feature_staked_fbtc_detail_records"
    )
    op.drop_index(
        "feature_staked_fbtc_detail_records_protocol_block_desc_index", table_name="feature_staked_fbtc_detail_records"
    )
    op.drop_table("feature_staked_fbtc_detail_records")
    # ### end Alembic commands ###
