"""add column to contracts table

Revision ID: 832fa52da346
Revises: aa99dd347ef1
Create Date: 2024-08-05 19:33:42.496838

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "832fa52da346"
down_revision: Union[str, None] = "aa99dd347ef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.add_column(
        "contracts",
        sa.Column(
            "deployed_code_hash",
            sa.VARCHAR(),
            sa.Computed(
                "encode(digest('0x'||encode(deployed_code, 'hex'), 'sha256'), 'hex')",
            ),
            nullable=True,
        ),
    )
    op.add_column("contracts", sa.Column("transaction_from_address", postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "transaction_from_address")
    op.drop_column("contracts", "deployed_code_hash")
    # ### end Alembic commands ###
