"""sync 1.0.0

Revision ID: ab4e180ea7a0
Revises: 3c7ea7b95dc5
Create Date: 2025-02-14 11:27:59.209992

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import ARRAY, BIGINT, BOOLEAN, INTEGER, NUMERIC, TIMESTAMP, VARCHAR
from sqlalchemy.dialects.postgresql import BYTEA

# revision identifiers, used by Alembic.
revision: str = "ab4e180ea7a0"
down_revision: Union[str, None] = "3c7ea7b95dc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nft_transfers",
        sa.Column("transaction_hash", BYTEA, nullable=False),
        sa.Column("block_hash", BYTEA, nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("token_id", NUMERIC(78, 0), nullable=False),
        sa.Column("from_address", BYTEA, nullable=True),
        sa.Column("to_address", BYTEA, nullable=True),
        sa.Column("token_address", BYTEA, nullable=True),
        sa.Column("value", NUMERIC(100, 0), nullable=True),
        sa.Column("block_number", BIGINT, nullable=False),
        sa.Column("block_timestamp", TIMESTAMP(timezone=False), nullable=False),
        sa.Column("create_time", TIMESTAMP(timezone=False), nullable=True),
        sa.Column("update_time", TIMESTAMP(timezone=False), nullable=True),
        sa.Column("reorg", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint(
            "transaction_hash",
            "block_timestamp",
            "block_number",
            "log_index",
            "block_hash",
            "token_id",
            name="nft_transfers_pkey",
        ),
    )
    op.add_column("tokens", sa.Column("no_balance_of", BOOLEAN(), nullable=True, default=False))
    op.add_column("tokens", sa.Column("fail_balance_of_count", INTEGER(), nullable=True, default=0))
    op.add_column("tokens", sa.Column("no_total_supply", BOOLEAN(), nullable=True, default=False))
    op.add_column("tokens", sa.Column("fail_total_supply_count", INTEGER(), nullable=True, default=0))
    op.add_column("tokens", sa.Column("tags", ARRAY(VARCHAR()), nullable=True))
    op.add_column("tokens", sa.Column("succeed_balance_of_count", INTEGER(), nullable=True, default=0))
    op.drop_constraint("address_token_balances_pkey", "address_token_balances", type_="primary")
    op.create_primary_key(
        "address_token_balances_pkey",
        "address_token_balances",
        ["address", "token_address", "token_id", "block_number", "block_timestamp"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nft_transfers")
    op.drop_column("tokens", "no_balance_of")
    op.drop_column("tokens", "fail_balance_of_count")
    op.drop_column("tokens", "no_total_supply")
    op.drop_column("tokens", "fail_total_supply_count")
    op.drop_column("tokens", "tags")
    op.drop_column("tokens", "succeed_balance_of_count")
    op.drop_constraint("address_token_balances_pkey", "address_token_balances", type_="primary")
    op.create_primary_key(
        "address_token_balances_pkey",
        "address_token_balances",
        ["address", "token_address", "token_id", "block_number"],
    )
