chain_id: 56

uniswap_v3_job:
  # empty means no filter. only work in price job
  pool_address:
    - '0xe2bb11d6b6a39e55762f5e14d632f0981198b3a7'

  # works in price\token job
  jobs:
    - type: swapsicle  # thena`
      factory address: '0x306f06c147f064a010530292a1eb6737c3e378e4'
      position_token_address: '0xa51adb08cbe6ae398046a23bec013979816b77ab'

export_tokens_and_transfers_job:
  filter_token_address:
    - '0xa51adb08cbe6ae398046a23bec013979816b77ab'