WITH aggregated_stats AS (SELECT address,
                                 SUM(txn_in_cnt)               AS total_txn_in_cnt,
                                 SUM(txn_out_cnt)              AS total_txn_out_cnt,
                                 SUM(txn_in_value)             AS total_txn_in_value,
                                 SUM(txn_out_value)            AS total_txn_out_value,
                                 SUM(internal_txn_in_cnt)      AS total_internal_txn_in_cnt,
                                 SUM(internal_txn_out_cnt)     AS total_internal_txn_out_cnt,
                                 SUM(internal_txn_in_value)    AS total_internal_txn_in_value,
                                 SUM(internal_txn_out_value)   AS total_internal_txn_out_value,
                                 SUM(erc20_transfer_in_cnt)    AS total_erc20_transfer_in_cnt,
                                 SUM(erc20_transfer_out_cnt)   AS total_erc20_transfer_out_cnt,
                                 SUM(erc721_transfer_in_cnt)   AS total_erc721_transfer_in_cnt,
                                 SUM(erc721_transfer_out_cnt)  AS total_erc721_transfer_out_cnt,
                                 SUM(erc1155_transfer_in_cnt)  AS total_erc1155_transfer_in_cnt,
                                 SUM(erc1155_transfer_out_cnt) AS total_erc1155_transfer_out_cnt,
                                 SUM(txn_in_error_cnt)         AS total_txn_in_error_cnt,
                                 SUM(txn_out_error_cnt)        AS total_txn_out_error_cnt,
                                 SUM(txn_self_cnt)             AS total_txn_self_cnt,
                                 SUM(txn_self_error_cnt)       AS total_txn_self_error_cnt,
                                 SUM(gas_in_used)              AS total_gas_in_used,
                                 SUM(l2_txn_in_fee)            AS total_l2_txn_in_fee,
                                 SUM(l1_txn_in_fee)            AS total_l1_txn_in_fee,
                                 SUM(txn_in_fee)               AS total_txn_in_fee,
                                 SUM(gas_out_used)             AS total_gas_out_used,
                                 SUM(l2_txn_out_fee)           AS total_l2_txn_out_fee,
                                 SUM(l1_txn_out_fee)           AS total_l1_txn_out_fee,
                                 SUM(txn_out_fee)              AS total_txn_out_fee
                          FROM daily_wallet_address_stats
                          GROUP BY address)

INSERT
INTO wallet_addresses
(address,
 txn_in_cnt,
 txn_out_cnt,
 txn_in_value,
 txn_out_value,
 internal_txn_in_cnt,
 internal_txn_out_cnt,
 internal_txn_in_value,
 internal_txn_out_value,
 erc20_transfer_in_cnt,
 erc20_transfer_out_cnt,
 erc721_transfer_in_cnt,
 erc721_transfer_out_cnt,
 erc1155_transfer_in_cnt,
 erc1155_transfer_out_cnt,
 txn_in_error_cnt,
 txn_out_error_cnt,
 txn_self_cnt,
 txn_self_error_cnt,
 gas_in_used,
 l2_txn_in_fee,
 l1_txn_in_fee,
 txn_in_fee,
 gas_out_used,
 l2_txn_out_fee,
 l1_txn_out_fee,
 txn_out_fee)
SELECT address,
       total_txn_in_cnt,
       total_txn_out_cnt,
       total_txn_in_value,
       total_txn_out_value,
       total_internal_txn_in_cnt,
       total_internal_txn_out_cnt,
       total_internal_txn_in_value,
       total_internal_txn_out_value,
       total_erc20_transfer_in_cnt,
       total_erc20_transfer_out_cnt,
       total_erc721_transfer_in_cnt,
       total_erc721_transfer_out_cnt,
       total_erc1155_transfer_in_cnt,
       total_erc1155_transfer_out_cnt,
       total_txn_in_error_cnt,
       total_txn_out_error_cnt,
       total_txn_self_cnt,
       total_txn_self_error_cnt,
       total_gas_in_used,
       total_l2_txn_in_fee,
       total_l1_txn_in_fee,
       total_txn_in_fee,
       total_gas_out_used,
       total_l2_txn_out_fee,
       total_l1_txn_out_fee,
       total_txn_out_fee

FROM aggregated_stats

ON CONFLICT (address)
    DO UPDATE SET txn_in_cnt               = EXCLUDED.txn_in_cnt,
                  txn_out_cnt              = EXCLUDED.txn_out_cnt,
                  txn_in_value             = EXCLUDED.txn_in_value,
                  txn_out_value            = EXCLUDED.txn_out_value,
                  internal_txn_in_cnt      = EXCLUDED.internal_txn_in_cnt,
                  internal_txn_out_cnt     = EXCLUDED.internal_txn_out_cnt,
                  internal_txn_in_value    = EXCLUDED.internal_txn_in_value,
                  internal_txn_out_value   = EXCLUDED.internal_txn_out_value,
                  erc20_transfer_in_cnt    = EXCLUDED.erc20_transfer_in_cnt,
                  erc20_transfer_out_cnt   = EXCLUDED.erc20_transfer_out_cnt,
                  erc721_transfer_in_cnt   = EXCLUDED.erc721_transfer_in_cnt,
                  erc721_transfer_out_cnt  = EXCLUDED.erc721_transfer_out_cnt,
                  erc1155_transfer_in_cnt  = EXCLUDED.erc1155_transfer_in_cnt,
                  erc1155_transfer_out_cnt = EXCLUDED.erc1155_transfer_out_cnt,
                  txn_in_error_cnt         = EXCLUDED.txn_in_error_cnt,
                  txn_out_error_cnt        = EXCLUDED.txn_out_error_cnt,
                  txn_self_cnt             = EXCLUDED.txn_self_cnt,
                  txn_self_error_cnt       = EXCLUDED.txn_self_error_cnt,
                  gas_in_used              = EXCLUDED.gas_in_used,
                  l2_txn_in_fee            = EXCLUDED.l2_txn_in_fee,
                  l1_txn_in_fee            = EXCLUDED.l1_txn_in_fee,
                  txn_in_fee               = EXCLUDED.txn_in_fee,
                  gas_out_used             = EXCLUDED.gas_out_used,
                  l2_txn_out_fee           = EXCLUDED.l2_txn_out_fee,
                  l1_txn_out_fee           = EXCLUDED.l1_txn_out_fee,
                  txn_out_fee              = EXCLUDED.txn_out_fee;