name: Hemera Indexer Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hemera
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      LINEA_PUBLIC_NODE_RPC_URL: '${{ secrets.LINEA_PUBLIC_NODE_RPC_URL }}'
      POSTGRES_USER: hemera
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgresql://hemera:password@localhost:5432/hemera
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry update
          poetry install -v
          poetry show

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=\$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Verify PYTHONPATH
        run: echo $PYTHONPATH

      - name: Init database
        run: |
          export PYTHONPATH=$(pwd)
          make init_db

      - name: Pipeline Test with pytest
        run: |
          export PYTHONPATH=$(pwd)
          make test pipeline
